Repository tekdi/eg-backend, pull requests merged in 2024-09, with the labels that each got.

#1471 Bug #226296 [BE] Pagination issue for pc learners facilitator list resolved
  src/src/program-coordinator/program-coordinator.service.ts
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#1473 Bug #226296 [BE] Pc learner facilitator list pagination fix
  src/src/program-coordinator/program-coordinator.service.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#1474 Merge `Release 2.6.0` into `Master(v2.5.5)`
  src/src/beneficiaries/beneficiaries.controller.ts
  src/src/beneficiaries/beneficiaries.module.ts
  src/src/beneficiaries/beneficiaries.service.ts
  src/src/camp/camp.service.ts
  src/src/enum/enum.json
  src/src/exam/exam.module.ts
  src/src/exam/exam.service.ts
  src/src/facilitator/facilitator.service.ts
  src/src/program-coordinator/program-coordinator.service.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 4

#1477 Bug #226434 [BE] : PC user | Learner List | Enrollment name data is missing in List API
  src/src/program-coordinator/program-coordinator.service.ts
Labels: enhancement, Review effort [1-5]: 1

#1476 Customer Request #226429 [BE] PC learner verification flow
  src/src/enum/enum.json
  src/src/program-coordinator/program-coordinator.controller.ts
  src/src/program-coordinator/program-coordinator.module.ts
  src/src/program-coordinator/program-coordinator.service.ts
Labels: enhancement, Review effort [1-5]: 3

#1480 Merge `Release 2.5.6` into `Master`
  src/src/program-coordinator/program-coordinator.service.ts
Labels: enhancement

#1479 Bug #226455 [BE] : Prerak List | Incorrect Validation on Prerak list API and Bug #226457 [BE] : ADMIN | PC | Prerak list | Filter is not working for District and block
  src/src/program-coordinator/program-coordinator.service.ts
Labels: enhancement, Review effort [1-5]: 3

#1484 [BE] Enum changes for exam status
  src/src/enum/enum.json
Labels: enhancement, Review effort [1-5]: 2

#1486 Filter added
  src/src/program-coordinator/program-coordinator.service.ts
Labels: enhancement, Review effort [1-5]: 2

#1487 Task #224927 [BE] Sonar issues fix
  src/src/beneficiaries/beneficiaries.service.ts
  src/src/camp/camp.service.ts
  src/src/common/middlewares/ip.middleware.ts
  src/src/cron/faAttendanceProcessing.cron.ts
  src/src/cron/faFaceIndexing.cron.ts
  src/src/cron/onestStatusUpdate.cron.ts
  src/src/cron/prepareCertificateHtml.cron.ts
  src/src/events/events.service.ts
  src/src/exam/exam.result.pattern.ts
  src/src/exam/exam.service.ts
  src/src/lms/dto/lms-certificate.dto.ts
  src/src/lms/dto/lms-test-tracking.dto.ts
  src/src/modules/board/board.controller.ts
  src/src/observations/dto/field-responses-search.dto.ts
  src/src/observations/dto/field-responses.dto.ts
  src/src/observations/dto/field-search.dto.ts
  src/src/observations/dto/observation-fields-search.dto.ts
  src/src/observations/dto/observation-fields.dto.ts
  src/src/observations/dto/observation-search.dto.ts
  src/src/observations/observations.module.ts
  src/src/observations/observations.service.ts
  src/src/onestusertrack/onestusertrack.controller.ts
  src/src/onestusertrack/onestusertrack.service.ts
  src/src/program-coordinator/program-coordinator.module.ts
  src/src/sessions/sessions.service.ts
  src/src/upload-file/upload-file.service.ts
  src/src/user/user.service.ts
  src/src/userauth/userauth.module.ts
  src/src/userauth/userauth.service.ts
  src/src/volunteer/volunteer.controller.ts
  src/src/volunteer/volunteer.module.ts
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#1485 Merge Release 2.5.7 into release-2.7.0 [BE] Conflicts merging 2.5.7 in 2.7.0
  src/src/beneficiaries/beneficiaries.service.ts
  src/src/enum/enum.json
  src/src/program-coordinator/program-coordinator.controller.ts
  src/src/program-coordinator/program-coordinator.module.ts
  src/src/program-coordinator/program-coordinator.service.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 4

#1488 Merge `Release 2.5.7(v2.6.0)` into `Master`
  src/src/enum/enum.json
  src/src/program-coordinator/program-coordinator.controller.ts
  src/src/program-coordinator/program-coordinator.module.ts
  src/src/program-coordinator/program-coordinator.service.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#1491 Bug #226565 [BE] Exam subject result changes with results
  src/src/exam/exam.service.ts
Labels: enhancement, Review effort [1-5]: 2

#1492 added search with id
  src/src/exam/exam.service.ts
Labels: enhancement, Review effort [1-5]: 2

#1493 Changes in certificate
  src/src/lms/templates/main_camp_training.ts
  src/src/lms/templates/pcr_training.ts
  src/src/lms/templates/pragati_orientation.ts
Labels: enhancement, Review effort [1-5]: 2

#1495 Task #224927: [BE] Sonar cloud issue solve
  src/src/userauth/userauth.service.ts
Labels: Review effort [1-5]: 1, bug_fix

#1494 [BE] Exam-upload-flow-modifications
  src/src/exam/exam.service.ts
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#1496 Merge `Release 2.6.1` into `Master`
  src/src/exam/exam.service.ts
  src/src/lms/templates/main_camp_training.ts
  src/src/lms/templates/pcr_training.ts
  src/src/lms/templates/pragati_orientation.ts
Labels: enhancement, Bug fix

#1497 Merge `Master(V2.6.1)` into `release-2.7.0`
  src/src/exam/exam.service.ts
  src/src/lms/templates/main_camp_training.ts
  src/src/lms/templates/pcr_training.ts
  src/src/lms/templates/pragati_orientation.ts
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#1501 Bug #226689 [BE] Verify-PSYC-validation-message-added
  src/src/beneficiaries/beneficiaries.service.ts
Labels: enhancement, Review effort [1-5]: 1, bug_fix

#1498 Task #224927: [BE] Sonar cloud issue solve
  src/src/onestusertrack/dto/create-onestusertrack.dto.ts
  src/src/onestusertrack/dto/update-onestusertrack.dto.ts
  src/src/onestusertrack/entities/onestusertrack.entity.ts
  src/src/organisation/dto/create-organisation.dto.ts
  src/src/organisation/dto/update-organisation.dto.ts
  src/src/organisation/entities/organisation.entity.ts
  src/src/pcrscores/dto/create-pcrscore.dto.ts
  src/src/pcrscores/dto/update-pcrscore.dto.ts
  src/src/pcrscores/entities/pcrscore.entity.ts
  src/src/references/dto/create-reference.dto.ts
  src/src/references/dto/update-reference.dto.ts
  src/src/references/entities/reference.entity.ts
  src/src/services/hasura/hasura.service.ts
  src/src/subjects/dto/create-subjects.dto.ts
  src/src/subjects/dto/update-subjects.dto.ts
  src/src/subjects/entities/subjects.entity.ts
  src/src/user/user.service.ts
  src/src/userauth/userauth.service.ts
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#1504 Task #224927: [BE] Sonar cloud issue solve
  src/src/comments/entities/comment.entity.ts
  src/src/cron/onestStatusUpdate.cron.ts
  src/src/events/entities/event.entity.ts
  src/src/exam/exam.service.ts
  src/src/facilitator/dto/create-facilitator.dto.ts
  src/src/facilitator/facilitator.service.ts
  src/src/hasura/hasura.service.ts
  src/src/lms/lms.service.ts
  src/src/pcrscores/pcrscores.service.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#1506 Bug #226949 [BE] Psyc-exam-fee-document-validation added
  src/src/exam/exam.service.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#1507 Bug #227149 [BE] Registred in neev camp learner reassing camp issue fix
  src/src/camp/camp.service.ts
Labels: Bug fix, Review effort [1-5]: 2

#1508 validation added in psyc
  src/src/exam/exam.service.ts
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#1505 sonar issue solved
  src/src/observations/observations.service.ts
  src/src/program-coordinator/program-coordinator.service.ts
Labels: Review effort [1-5]: 2, bug_fix

#1531 merge Release 2.7.1 into master
  src/src/facilitator/facilitator.service.ts
  src/src/program-coordinator/program-coordinator.service.ts
Labels: enhancement, Bug fix
