Repository tekdi/eg-backend, pull requests merged in 2024-07, with the labels that each got.

#1334 Bug #223339 [BE] : Prerak Onboarding | Incorrect Address field required message is showing
  src/src/userauth/userauth.service.ts
Labels: enhancement, Review effort [1-5]: 1

#1335 Customer Request #223348 [BE] : Asc and desc sorting should happen by name
  src/src/beneficiaries/beneficiaries.service.ts
Labels: enhancement, Review effort [1-5]: 2

#1337 Task #223354 [BE] : Exam Schedule | Adding validation for the publish subject date
  src/src/exam/exam.service.ts
Labels: enhancement, Review effort [1-5]: 2

#1339 Customer Request #223414 [BE] : Education Details | Remove NA from all drop outs
  src/src/enum/enum.json
Labels: enhancement, Review effort [1-5]: 1

#1340 Task #223418 [BE] Get Learner Assessment score subject wise
  src/src/beneficiaries/beneficiaries.controller.ts
  src/src/beneficiaries/beneficiaries.service.ts
Labels: enhancement, Other, Review effort [1-5]: 3

#1342 Task #223418 [BE] Get Learner Assessment score subject wise
  src/src/beneficiaries/beneficiaries.service.ts
Labels: enhancement, Review effort [1-5]: 3

#1343 Merge `Release 2.2.5` into `feat-register-revamp`
  src/src/beneficiaries/beneficiaries.service.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#1344 Customer Request #222017 [BE] PCR Camp list ready to close camp
  src/src/camp/camp.core.service.ts
Labels: enhancement, Review effort [1-5]: 2

#1346 Customer Request #222089 [BE] Add validation in Session for main camp check All assessment removed
  src/src/sessions/sessions.service.ts
Labels: Bug fix, Review effort [1-5]: 2

#1352 [BE] Conflicts merging 2.4.0 to 2.3.0
  src/src/beneficiaries/beneficiaries.controller.ts
  src/src/beneficiaries/beneficiaries.service.ts
  src/src/camp/camp.controller.ts
  src/src/camp/camp.core.service.ts
  src/src/camp/camp.module.ts
  src/src/camp/camp.service.ts
  src/src/cron/cron.module.ts
  src/src/cron/onestStatusUpdate.cron.ts
  src/src/enum/enum.json
  src/src/exam/exam.service.ts
  src/src/modules/auth/auth.controller.ts
  src/src/modules/auth/auth.service.ts
  src/src/modules/geolocation/geolocation.controller.ts
  src/src/modules/geolocation/geolocation.service.ts
  src/src/onestusertrack/onestusertrack.controller.ts
  src/src/onestusertrack/onestusertrack.service.ts
  src/src/pcrscores/pcrscores.service.ts
  src/src/sessions/sessions.module.ts
  src/src/sessions/sessions.service.ts
  src/src/userauth/userauth.service.ts
  src/src/volunteer/volunteer.module.ts
  src/src/volunteer/volunteer.service.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 4, Other

#1351 [BE] Task #222944 Facilittaor revamp changes and modifications
  src/src/modules/auth/auth.service.ts
  src/src/userauth/userauth.service.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#1354 Bug #223826 [BE] : Unable to create camp - getting an error that learner id does not exists
  src/src/camp/camp.controller.ts
  src/src/camp/camp.service.ts
Labels: Bug fix, Review effort [1-5]: 2

#1357 [BE] Customer Request #223854 Beneficiary-enrollment-validation-added
  src/src/beneficiaries/beneficiaries.controller.ts
  src/src/beneficiaries/beneficiaries.service.ts
Labels: enhancement, Tests, Review effort [1-5]: 3

#1358 Task #223862 [BE] Validation to check all fields are fill for that status change
  src/src/facilitator/facilitator.controller.ts
  src/src/facilitator/facilitator.service.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 4

#1359 [BE] Customer Request #223854 Prefix removed from the return array
  src/src/beneficiaries/beneficiaries.service.ts
Labels: Bug fix, Review effort [1-5]: 2

#1361 [BE] Customer Request #223868 5th-standard-flag-added
  src/src/beneficiaries/beneficiaries.service.ts
Labels: enhancement, Review effort [1-5]: 1

#1360 Task #223862 [BE] Validation to check all fields are fill for that status change
  src/src/facilitator/facilitator.service.ts
Labels: enhancement, Review effort [1-5]: 2

#1362 [BE] Customer Request #223871 Learner-enrollment-valdiation-added-to-the-edit-api
  src/src/beneficiaries/beneficiaries.service.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#1353 [BE] Customer Request #223777 Reject-learner-for-standard-below-5th
  src/src/beneficiaries/beneficiaries.service.ts
  src/src/enum/enum.json
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#1366 [BE] Customer Request #224150 Enrollment-enrolled-new-modification
  src/src/beneficiaries/beneficiaries.service.ts
  src/src/enum/enum.json
Labels: enhancement, Review effort [1-5]: 5

#1369 [BE] Customer Request #224176 Subject-type-added-to-subjects
  src/src/exam/exam.service.ts
  src/src/modules/board/board.service.ts
Labels: enhancement, Review effort [1-5]: 2
